      const classAStudents = [
        {  roll: 101, name: "Jiya Kyada"},
        {  roll: 102, name: "Shah Dhvani Hitesh"},
        {  roll: 103, name: "Saraya Mohit Haresh"},
        {  roll: 104, name: "Zalavadiya Heet Siddharth"},
        {  roll: 105, name: "Darshil Dobariya"},
        {  roll: 106, name: "Nafisa Gandhi"},
        {  roll: 107, name: "Vasani Yashvi Niteshbhai"},
        {  roll: 108, name: "Delvadiya Manavkumar Kirtibhai"},
        {  roll: 109, name: "Ashara Palak Gopalbhai"},
        {  roll: 110, name: "Lunagariya Greshi Kamleshbhai"},
        {  roll: 111, name: "Nanavati Shrushti Gargesh"},
        {  roll: 112, name: "Ranpara Jay Manishbhai"},
        {  roll: 113, name: "Disha Mehta"},
        {  roll: 114, name: "Thummar Niraj Bhaveshbhai"},
        {  roll: 115, name: "Kachhava Nakul Umeshbhai"},
        {  roll: 116, name: "Kanabar Urva Darshanbhai"},
        {  roll: 117, name: "Nakar Dhruvil Hitesh"},
        {  roll: 118, name: "Poshiya Priyanshi Ajaybhai"},
        {  roll: 119, name: "Baravalia Dharitri Manharbhai"},
        {  roll: 120, name: "Muchhara Kashish Hiteshbhai"},
        {  roll: 120, name: "Muchhara Kashish Hiteshbhai"},
        {  roll: 120, name: "Muchhara Kashish Hiteshbhai"},
        {  roll: 121, name: "Chauhan Aditya Sureshbhai"},
        {  roll: 122, name: "Harsora Sakshi Ajaybhai"},
        {  roll: 123, name: "Katrodiya Sahil Rajeshbhai"},
        {  roll: 124, name: "Trambadiya Parikshit Parimalbhai"},
        {  roll: 125, name: "Padariya Preya Parasbhai"},
        {  roll: 126, name: "Gambhava Krushiben Manojbhai"},
        {  roll: 127, name: "Jadeja Vishwrajsinh Krushnasinh"},
        {  roll: 128, name: "Patel Jiya Sandipbhai"},
        {  roll: 129, name: "Pipalava Smit Ashvinbhai"},
        {  roll: 130, name: "Gohil Harshrajsinh Jitendrasinh"},
        {  roll: 131, name: "Kathiriya Arshi Keshubhai"},
        {  roll: 132, name: "Undhad Vishwa Rajesh"},
        {  roll: 133, name: "Diya Raiyani"},
        {  roll: 134, name: "Chavda Maulik Vinodbhai"},
        {  roll: 135, name: "Chavda Priyanka Prabodhbhai"},
        {  roll: 136, name: "Chavda Virendrasinh Ashwinbhai"},
        {  roll: 137, name: "Galani Krunal Chetanbhai"},
        {  roll: 138, name: "Kavar Suchi Vasantbhai"},
        {  roll: 139, name: "Odedara Nilesh Parbat"},
        {  roll: 140, name: "Vasani Dishita Nikhilkumar"},
        {  roll: 141, name: "Vachhani Vaishvi Manojkumar"},
        {  roll: 142, name: "Bhadania Ronit Yatinbhai"},
        {  roll: 143, name: "Chauhan Jenil Virenbhai"},
        {  roll: 144, name: "Virpara Krisha Rajeshbhai"},
        {  roll: 145, name: "Chandra Darshit Hiteshbhai"},
        {  roll: 146, name: "Detroja Ruchit Arvindbhai"},
        {  roll: 147, name: "Kapuriya Hepin Pravinbhai"},
        {  roll: 148, name: "Gohel Smit Ashvinbhai"},
        {  roll: 149, name: "Patel Kirtan Amitbhai"},
        {  roll: 150, name: "Ginoya Deep Kantilal"},
        {  roll: 151, name: "Marvaniya Jainish Dharmendrabhai"},
        {  roll: 152, name: "Ajudiya Yash Nareshbhai"},
        {  roll: 153, name: "Manas Borisagar"},
        {  roll: 154, name: "Joshi Soham Kamleshbhai"},
        {  roll: 155, name: "Kakadiya Khilan Manishbhai"},
        {  roll: 156, name: "Sidhdhapura Dhaval Dharmeshbhai"},
        {  roll: 157, name: "Sitapara Aryan Sunilbhai"},
        {  roll: 158, name: "Bhatasana Nainshi Pareshbhai"},
        {  roll: 159, name: "Malvaniya Viraj Jatinbhai"},
        {  roll: 160, name: "Tanisha Pambhar"},
        {  roll: 161, name: "Padshala Kuldeep Rajendrakumar"},
        {  roll: 162, name: "Bhimani Vishva Manishbhai"},
        {  roll: 163, name: "Karan Anushka Pintubhai"},
        {  roll: 164, name: "Vyas Kavya Sachin"},
        {  roll: 165, name: "Kamani Purna Hareshbhai"},
        {  roll: 166, name: "Mori Nandita Renishkumar"},
        {  roll: 167, name: "Ratanghayra Pankti Himanshu"},
        {  roll: 168, name: "Rupala Nikhil Kashmeeraben"},
        {  roll: 169, name: "Jadeja Shivrajsinh Girirajsinh"},
        {  roll: 170, name: "Hirva Satani"},
        {  roll: 171, name: "Raiyani Jenil Sanjaybhai"},
        {  roll: 172, name: "Chandpa Prince Sureshbhai"},
        {  roll: 173, name: "Faldu Vrajesh Sanjaybhai"},
        {  roll: 174, name: "Khambholiya Manya Parasharbhai"},
        {  roll: 175, name: "Prajapati Kaivalya Samir"},
        {  roll: 176, name: "Moral Aadit Shaileshbhai"},
        {  roll: 177, name: "Shihora Vibhu Chetanbhai"},
        {  roll: 178, name: "Kanani Kruti Jayeshbhai"},
        {  roll: 179, name: "Karoliya Princekumar Sandipbhai"},
        {  roll: 180, name: "Khunt Rutvi Hiteshbhai"},
        {  roll: 181, name: "Charadva Abhishek Virenbhai"},
        {  roll: 182, name: "Dave Krisha Kalpeshbhai"},
        {  roll: 183, name: "Janvi Kalaria"},
        {  roll: 184, name: "Rajwani Rohan Malik"},
        {  roll: 185, name: "Rana Parthrajsinh Bhupatsinh"},
        {  roll: 186, name: "Solanki Ronak Arvindbhai"},
        {  roll: 187, name: "Panchal Vedantkumar Niravbhai"},
        {  roll: 188, name: "Ambasana Venisha Hitenbhai"},
        {  roll: 189, name: "Raichura Smeet Rohitkumar"},
        {  roll:190, name: "Gambhava Mirali Sureshbhai"},
        {  roll:191, name: "Dave Dhruv Viralkumar"},
        {  roll:192, name: "Ghetiya Ritu Pankajbhai"},
        {  roll:193, name: "Radhanpara Saumya Jatinbhai"},
        {  roll:194, name: "Yadav Gaurav Kaushikbhai"},
        {  roll:195, name: "Buddhadev Misri Sanjaybhai"},
        {  roll:196, name: "Joshi Kairav Paren"},
        {  roll:197, name: "Savaliya Dhruvi Bharatbhai"},
        {  roll:198, name: "Radhanpura Jeel Nimish"},
        {  roll:199, name: "Savaliya Priyanshi Sureshbhai"},
        {  roll:200, name: "Zala Bhavyadeepsinh Pruthvirajsinh"},
        {  roll:201, name: "Sinha Milankumar Sujitkumar"},
        {  roll:202, name: "Lakhtaria Kevin Homin"},
        {  roll:203, name: "Moliya Kartavya Bhaveshbhai"},
        {  roll:204, name: "Monpara Nij Hareshbhai"},
        {  roll:205, name: "Divya Thakar"},
        {  roll:206, name: "Mendapara Piyu Amishbhai"},
        {  roll:207, name: "Pandya Karan Tusharbhai"},
        {  roll:208, name: "Raval Meet Mohitkumar"},
        {  roll:209, name: "Virpariya Heer Manishbhai"},
        {  roll:210, name: "Bhanushali Hiral Bhaven"},
        {  roll:211, name: "Kamaliya Akashkumar Rameshbhai"},
        {  roll:212, name: "Popat Honey Nileshbhai"},
        {  roll:213, name: "Badrakiya Meet Bharatbhai"},
        {  roll:214, name: "Kanani Kavit Nareshbhai"},
        {  roll:215, name: "Ambaliya Manan Jayeshbhai"},
        {  roll:216, name: "Hinsu Umang Bharatbhai"},
        {  roll:217, name: "Kakaniya Bhavy Niteshbhai"},
        {  roll:218, name: "Padia Kartik Balkrishna"},
        {  roll:219, name: "Mankada Hasan Shabbirhusain"},
        {  roll:220, name: "Mehta Dhairy Kalpeshbhai"},
        {  roll:221, name: "Mehta Het Lalitkumar"},
        {  roll:222, name: "Kahan Sanghani"},
        {  roll:223, name: "Gotani Himesh Sanjaybhai"},
        {  roll:224, name: "Narola Yash Nileshbhai"},
        {  roll:225, name: "Targata Dharmishtha Arjanbhai"},
        {  roll:226, name: "Bhuva Tirth Shaileshbhai"},
        {  roll:227, name: "Jadeja Yashraj Lakhdhirsinh"},
        {  roll:228, name: "Krisha Pujara"},
        {  roll:229, name: "Varsani Ritul Hirji"},
        {  roll:230, name: "Parmar Dhyey Dharmendra"},
        {  roll:231, name: "Shingala Mansi Rajeshbhai"},
        {  roll:232, name: "Dobariya Jeel Upendrabhai"},
        {  roll:233, name: "Khant Mannkumar Jigneshbhai"},
        {  roll:234, name: "Yadav Neel Hiteshbhai"},
        {  roll:235, name: "Andodariya Yash Maheshbhai"},
        {  roll:236, name: "Hirani Jeelkumar Sanjaybhai"},
        {  roll:237, name: "Mankad Shyamsundar Mitbhai"},
        {  roll:238, name: "Agavan Rohan Farukbhai"},
        {  roll:239, name: "Bhadja Zeel Satishkumar"},
        {  roll:240, name: "Shreya Vijaybhai Bhundia"},
        {  roll:241, name: "Aghara Keyur Hiteshbhai"},
        {  roll:242, name: "Buddhadev Deep Nitinbhai"},
        {  roll:243, name: "Godham Meet Maheshbhai"},
        {  roll:244, name: "Katariya Trisha Ashvinbhai"},
        {  roll:245, name: "Vekariya Jay Bipinbhai"},
        {  roll:246, name: "Rutvi Gautami"},
        {  roll:247, name: "Sankaliya Aryan Ashokbhai"},
        {  roll:248, name: "Ghadiya Yashvi Sanjaybhai"},
        {  roll:249, name: "Ved Chatvani"},
        {  roll:250, name: "Ghorai Swati Sanjib"},
        {  roll:251, name: "Karena Radhika Bharatbhai"},
        {  roll:252, name: "Pandya Kruti Tusharbhai"},
        {  roll:253, name: "Patel Tejkumar Niteshbhai"},
        {  roll:254, name: "Sagpariya Mahee Nitinbhai"},
        {  roll:255, name: "Sherasiya Shyam Sureshbhai"},
        {  roll:256, name: "Liya Hirvita Rajendra"},
        {  roll:257, name: "Ahir Krishna Manishbhai"},
        {  roll:258, name: "Parmar Devanshu Gopalbhai"},
        {  roll:259, name: "Tivari Astha Sureshbhai"},
        {  roll:260, name: "Pal Kana Odedra"},
        {  roll:261, name: "Sorathiya Nabhag Sanjaybhai"},
        {  roll:262, name: "Chauhan Vishal Girishbhai"},
        {  roll:263, name: "Kuchhadiya Vanita Bhima"},
        {  roll:264, name: "Bhimani Naman Chiragbhai"},
        {  roll:265, name: "Diyora Miraj Bhaveshbhai"},
        {  roll:266, name: "Gajera Rakshit Ketanbhai"},
        {  roll:267, name: "Parmar Darpan Jitendra"},
        {  roll:268, name: "Trivedi Manan Vijaykumar"},
        {  roll:269, name: "Dave Maharshi Kirtikumar"},
        {  roll:270, name: "Param Rameshbhai Kotadiya"},
        {  roll:271, name: "Patel Archi Pradipbhai"},
        {  roll:272, name: "Saradhara Yug Vrajbhushanbhai"},
        {  roll:273, name: "Padhariya Ruturajsinh Sureshbhai"},
        {  roll:274, name: "Vegad Jenil Ashokbhai"},
        {  roll:275, name: "Patani Kismatbanu Shahidbhai"},
        {  roll:276, name: "Savaliya Jinesh Kantilal"},
        {  roll:277, name: "Tank Darshan Chetanbhai"},
        {  roll:278, name: "Ghodasara Dev Ketanbhai"},
        {  roll:279, name: "Pithadiya Yash Devendrabhai"},
        {  roll:280, name: "Gohel Jenil Amitkumar"},
      ];

      const classBStudents = [
        { roll: 301, name: "Javiya Nirali Ramjibhai" },
        { roll: 302, name: "Kothadia Jal Hiteshkumar"},
        { roll: 303, name: "Parmar Bhavik Arjanbhai" },
        { roll: 304, name: "Ramani Manav Satishbhai"},
        { roll: 305, name: "Rathod Paras Ravibhai"},
        { roll: 306, name: "Chauhan Smit Hasmukhbhai"},
        { roll: 307, name: "Lunagariya Tirth Jayeshbhai"},
        { roll: 308, name: "Bhatti Jiya Pankajbhai"},
        { roll: 309, name: "Dhaduk Vandan Dipakbhai"},
        { roll: 310, name: "Khorajiya Mahir Mustufa"},
        { roll: 311, name: "Dangar Naimish Hasmukhbhai "},
        { roll: 312, name: "Sureja Vrunda Sumitbhai"},
        { roll: 313, name: "Manek Malay Rishibhai "},
        { roll: 314, name: "Raiyani Vishva Nileshbhai "},
        { roll: 315, name: "Santoki Sakshiben Devendrabhai "},
        { roll: 316, name: "Solanki Naimisha Ganeshbhai "},
        { roll: 317, name: "Taraviya Krutagn Dilipkumar "},
        { roll: 318, name: "Bhatti Hardvi Rajendrabhai "},
        { roll: 319, name: "Dobariya Rutvi Rasikbhai "},
        { roll: 320, name: "Gohel Darshan Kishorbhai "},
        { roll: 321, name: "Siddhpura Vrinda Nileshbhai"},
        { roll: 322, name: " Somaiya Nihal Dipak "},
        { roll: 323, name: "Vala Harsiddhiba Jayvirsinh "},
        { roll: 324, name: "Rankja Khushi Satishbhai "},
        { roll: 325, name: " Shingala Jina Dilipbhai "},
        { roll: 326, name: "Shingala Dharmik Dharmeshbhai "},
        { roll: 327, name: "Parsana Shubham Pareshbhai "},
        { roll: 328, name: "Mendpara Krishaben Hasmukhbhai "},
        { roll: 329, name: "Barevadiya Devarsh Harikrushnabhai "},
        { roll: 330, name: "Gopani Mitsu Bharatbhai "},
        { roll: 331, name: "Jamod Kashika Pravinbhai "},
        { roll: 332, name: "Kalola Hill Kishorbhai "},
        { roll: 333, name: "Pipaliya Meet Bharatbhai "},
        { roll: 334, name: "Sadhu Kuldeep Harshadkumar "},
        { roll: 335, name: "Dhandha Aayushi Sanatbhai "},
        { roll: 336, name: "Jadeja Riddhiba Jayendrasinh "},
        {roll: 337, name: "Kanjariya Radhika Mukeshbhai "},
        {roll: 338, name: " Joshi Vivek Bhaveshbhai "},
        {roll: 339, name: "Dashadiya Yash Kishorbhai "},
        {roll: 340, name: "Kanzariya Krunal Pravinbhai "},
        {roll: 341, name: "Jodhani Dhruvbhai Rajeshkumar "},
        {roll: 342, name: "Shivang Nandani "},
        {roll: 343, name: "Rangani Arpit Dilipbhai "},
        {roll: 344, name: "Ghodasara Yashvi Dhirajlal "},
        {roll: 345, name: "Rakhasiya Nikhil Hasmukhbhai "},
        {roll: 346, name: "Dhamsaniya Princyben Ashokbhai "},
        { roll: 347, name: "Tirth Gamara "},
        { roll: 348, name: "Mahek Patel"},
        { roll: 349, name: "Kasundra Prakruti Sanjaybhai "},
        { roll: 350, name: "Kacha Param Sanjay "},
        { roll: 351, name: "Sorathiya Mann Ashvinbhai "},
        { roll: 352, name: "Vansajaliya Ankit Hemantbhai "},
        { roll: 353, name: "Fultariya om "},
        { roll: 354, name: "Manvar Hemil Rakeshbhai "},
        { roll: 355, name: "Detroja Ujjwal Narendrabhai "},
        { roll: 356, name: "Hinsu Vraj Devjibhai "},
        { roll:357, name: "Vala Prashantkumar Maheshbhai "},
        { roll: 358, name: "Jadeja Manvendrasinh Jaydeepsinh "},
        { roll: 359, name: "Meghani Rishita Narendrabhai "},
        { roll: 360, name: "Hirani Tulsiben Rohitbhai "},
        { roll: 361, name: " Makwana Shraddha Shaileshbhai  "},
        { roll: 362, name: "Bhalala Het Lalitbhai"},
        { roll: 363, name: "Chotaliya Jenish Ashokbhai "},
        { roll: 364, name: "Detroja Sharadkumar Dilipbhai "},
        { roll: 365, name: "Kardani Prince Vipulbhai "},
        { roll: 366, name: "Ughreja Dax Ashokbhai "},
        { roll: 367, name: "Khambhala Tarkesh Vallabhbhai "},
        { roll: 368, name: "Sodha Kashwiniba Lakhansinh "},
        { roll: 369, name: "Vachhani Janvi Avinashbhi "},
        { roll: 370, name: "Dave Hetvi Gopalbhai "},
        { roll: 371, name: "Padia Harsh Jitendrabhai"},
        { roll: 372, name: "Umretiya Kush Bharatbhai "},
        { roll: 373, name: "Khokhar Dhruvi Govind"},
        { roll: 374, name: "Parmar Anirudhdha Govindbhai"},
        { roll: 375, name: "Bhimani Jeel Yogeshbhai "},
        { roll: 376, name: "Patel Neel Sanjaykumar "},
        { roll: 377, name: "Mehta Sneha Ashvinbhai "},
        { roll: 378, name: "Parekh Bhargav Sanjaybhai "},
        { roll: 379, name: "Sakariya Mihir Kishorbhai "},
        { roll: 380, name: "Gondaliya Shrijal Jayeshkumar "},
        { roll: 381, name: "Makvana Rutvik Kalpeshbhai "},
        { roll: 382, name: "Dodiya Riya Darshanbhai "},
        { roll: 383, name: "Limbasiya Deep Pareshbhai "},
        { roll: 384, name: "Parmar Dhruvi Nareshbhai "},
        { roll: 385, name: "Vishva Thesiya "},
        { roll: 386, name: "Dave Dhruv Yogeshkumar "},
        { roll: 387, name: "Lakkad Devisbhai Arvindbhai "},
        { roll: 388, name: "Dalsaniya Yashvi Jayeshkumar "},
        { roll: 389, name: "Bhuva Shivam Ashwinbhai "},
        { roll: 390, name: "Malaviya Mitul Mukeshbhai "},
        { roll: 391, name: "Solanki Aryan Valjibhai "},
        { roll: 392, name: "Vora Rudra Girishbhai "},
        { roll: 393, name: "Solanki Vishal Rameshbhai "},
        { roll: 394, name: "Vyas Jinal Amitbhai "},
        { roll: 395, name: "Savaliya Tirth Navnitbhai "},
        { roll: 396, name: "Vasani Daksh Nikhilkumar"},
        { roll: 397, name: "Kantesaria Pari Romalbhai "},
        { roll: 398, name: "Baraiya Yash Nileshbhai "},
        { roll: 399, name: "Goswami Rudra Nileshgar "},
        { roll: 400, name: "Ladani Mann Snehalbhai"},
        { roll: 401, name: "Parmar Uday Jagdishbhai "},
        { roll: 402, name: "Parsaniya Dhruvkumar Jayendrabhai "},
        { roll: 403, name: "Vagh Dhavalbhai Nareshbhai "},
        { roll: 404, name: "Ghoniya Vrunda Dilipbhai "},
        { roll: 405, name: "Sankhavara Prayag Mansukhlal "},
        { roll: 406, name: "Gohel Kuldeep Kishorbhai "},
        { roll: 407, name: "Bhoraniya Priya Sureshbhai "},
        { roll: 408, name: "Bajadiya Om Bhupatbhai"},
        { roll: 409, name: "Ghardeshiya Man Ashokbhai "},
        { roll: 410, name: "Harkhani Ronak Prafulbhai "},
        { roll: 411, name: "Aryansinh Lalakia "},
        { roll: 412, name: "Mendapara Utpal Shaileshbhai "},
        { roll: 413, name: "Bechra Diya Jayesh"},
        { roll: 414, name: "Mathakiya Navfal Kutbudin "},
        { roll: 415, name: "Kamaliya Manaliben Dineshbhai "},
        { roll: 416, name: "Vaghera Vaidika Hinaben "},
        { roll: 417, name: "Dave Krisha Satyakam"},
        { roll: 418, name: "Markana Nisarg Maheshbhai "},
        { roll: 419, name: "Bagda Sandipkumar Danabhai "},
        { roll: 420, name: "Vora Preet Chetankumar "},
        { roll: 421, name: "Dhamsaniya Dhvani Kishorbhai "},
        { roll: 422, name: "Mungara Meet Vithalbhai "},
        { roll: 423, name: "Hinsu Maitri Dipakbhai "},
        { roll: 424, name: "Mehta Vatsal Yogeshkumar "},
        { roll: 425, name: "Chadamiya Bhavy Babulal "},
        { roll: 426, name: "Bavaliya Tushar Pravinbhai"},
        { roll: 427, name: "Kotadia Richa Cheritkumar "},
        { roll: 428, name: "Chauhan Krutarth Rajubhai "},
        { roll: 429, name: "Sheth Harsh Ketanbhai "}];